CREATE TABLE IF NOT EXISTS DEPARTMENT (
  id   INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL
);
CREATE TABLE IF NOT EXISTS EMPLOYEE (
  id         INT AUTO_INCREMENT PRIMARY KEY,
  lname      VARCHAR(255) NOT NULL,
  mname      VARCHAR(255) NOT NULL,
  sname      VARCHAR(255) NOT NULL,
  date       DATE NOT NULL,
  salary     DOUBLE,
  department VARCHAR(255) NOT NULL
);