INSERT INTO DEPARTMENT VALUES(NULL , 'Recruters');
INSERT INTO DEPARTMENT VALUES(NULL , 'Developers');
INSERT INTO DEPARTMENT VALUES(NULL , 'Managers');
INSERT INTO DEPARTMENT VALUES(NULL , 'Testers');